# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/namanwahi/Downloads/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/namanwahi/Downloads/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/namanwahi/zombie_game_refactored

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/namanwahi/zombie_game_refactored

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/namanwahi/Downloads/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/namanwahi/Downloads/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/namanwahi/zombie_game_refactored/CMakeFiles /home/namanwahi/zombie_game_refactored/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/namanwahi/zombie_game_refactored/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zombie_game_refactored

# Build rule for target.
zombie_game_refactored: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zombie_game_refactored
.PHONY : zombie_game_refactored

# fast build rule for target.
zombie_game_refactored/fast:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/build
.PHONY : zombie_game_refactored/fast

Enemy.o: Enemy.cpp.o

.PHONY : Enemy.o

# target to build an object file
Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/Enemy.cpp.o
.PHONY : Enemy.cpp.o

Enemy.i: Enemy.cpp.i

.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/Enemy.cpp.i
.PHONY : Enemy.cpp.i

Enemy.s: Enemy.cpp.s

.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/Enemy.cpp.s
.PHONY : Enemy.cpp.s

geometry_utils.o: geometry_utils.cpp.o

.PHONY : geometry_utils.o

# target to build an object file
geometry_utils.cpp.o:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/geometry_utils.cpp.o
.PHONY : geometry_utils.cpp.o

geometry_utils.i: geometry_utils.cpp.i

.PHONY : geometry_utils.i

# target to preprocess a source file
geometry_utils.cpp.i:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/geometry_utils.cpp.i
.PHONY : geometry_utils.cpp.i

geometry_utils.s: geometry_utils.cpp.s

.PHONY : geometry_utils.s

# target to generate assembly for a file
geometry_utils.cpp.s:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/geometry_utils.cpp.s
.PHONY : geometry_utils.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/main.cpp.s
.PHONY : main.cpp.s

player.o: player.cpp.o

.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i

.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s

.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/player.cpp.s
.PHONY : player.cpp.s

rand_utils.o: rand_utils.cpp.o

.PHONY : rand_utils.o

# target to build an object file
rand_utils.cpp.o:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/rand_utils.cpp.o
.PHONY : rand_utils.cpp.o

rand_utils.i: rand_utils.cpp.i

.PHONY : rand_utils.i

# target to preprocess a source file
rand_utils.cpp.i:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/rand_utils.cpp.i
.PHONY : rand_utils.cpp.i

rand_utils.s: rand_utils.cpp.s

.PHONY : rand_utils.s

# target to generate assembly for a file
rand_utils.cpp.s:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/rand_utils.cpp.s
.PHONY : rand_utils.cpp.s

resource_bar.o: resource_bar.cpp.o

.PHONY : resource_bar.o

# target to build an object file
resource_bar.cpp.o:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/resource_bar.cpp.o
.PHONY : resource_bar.cpp.o

resource_bar.i: resource_bar.cpp.i

.PHONY : resource_bar.i

# target to preprocess a source file
resource_bar.cpp.i:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/resource_bar.cpp.i
.PHONY : resource_bar.cpp.i

resource_bar.s: resource_bar.cpp.s

.PHONY : resource_bar.s

# target to generate assembly for a file
resource_bar.cpp.s:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/resource_bar.cpp.s
.PHONY : resource_bar.cpp.s

texture_wrapper.o: texture_wrapper.cpp.o

.PHONY : texture_wrapper.o

# target to build an object file
texture_wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/texture_wrapper.cpp.o
.PHONY : texture_wrapper.cpp.o

texture_wrapper.i: texture_wrapper.cpp.i

.PHONY : texture_wrapper.i

# target to preprocess a source file
texture_wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/texture_wrapper.cpp.i
.PHONY : texture_wrapper.cpp.i

texture_wrapper.s: texture_wrapper.cpp.s

.PHONY : texture_wrapper.s

# target to generate assembly for a file
texture_wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/zombie_game_refactored.dir/build.make CMakeFiles/zombie_game_refactored.dir/texture_wrapper.cpp.s
.PHONY : texture_wrapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... zombie_game_refactored"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... geometry_utils.o"
	@echo "... geometry_utils.i"
	@echo "... geometry_utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... rand_utils.o"
	@echo "... rand_utils.i"
	@echo "... rand_utils.s"
	@echo "... resource_bar.o"
	@echo "... resource_bar.i"
	@echo "... resource_bar.s"
	@echo "... texture_wrapper.o"
	@echo "... texture_wrapper.i"
	@echo "... texture_wrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

